### ISSUE TITLE
3.6.11 under Plone 4.3.1 breaks numbered and bulleted lists

### ISSUE THREAD

**Issue by blackbronze979** [collective/collective.ckeditor#25]
We have Plone 4.3.1 (4306)  with ckeditor 3.6.11 both recently upgraded from 4.3.1 (without the hotfixes applied) and 3.6.10 respectively.  

When editing an already existing page the numbered lists are now showing up with the number hidden under the border of the editor with only the "." visible about 1 pixel to the right of the border.  The same thing with bulleted lists.  Indentation of new items doesn't work and keeps all lists flush against the border.

We have created ordered lists in the default TinyMCE version, saved the page, switched editor preference to CKEditor and edited the page.  All of the lists, included indented items, show up flush against the border.

We created a CSS for body.cke_show_borders and set "padding: 25px;".  This then allows us to see what the numbers are.  Indentation is still broken upon initial edit.  We then edit the page to include new numbered lists with indentation (which works).  We then switch back to TinyMCE and every ordered list appears exactly as the HTML source shows it should.

**Comment by gotcha** [comment]
As there was no answer, Ill close the issue. Feel free to reopen.
