### ISSUE TITLE
Support for Python 2.6 (Plone 4.1)

### ISSUE THREAD

**Issue by naro** [collective/collective.ckeditor#34]
Python2.6 does not support "{}".format() but requires "{0}".format() syntax

See https://github.com/collective/collective.ckeditor/blob/master/src/collective/ckeditor/browser/ckeditorview.py#L292 and https://github.com/collective/collective.ckeditor/blob/master/src/collective/ckeditor/browser/ckeditorview.py#L299

**Comment by davidamoros** [comment]
Hello,

This is still an issue (collective.ckeditor) for plone 4.1 and collective.ckeditor = 4.2.0.

The solution provided by @naro worked for me...

**Comment by gbastien** [comment]
Hi @davidamoros 

as gotcha said, just do a PR and this will be merged quickly...

Gauthier
