### ISSUE TITLE
Recent issues with Buildout and version 4.3.0b3

### ISSUE THREAD

**Issue by pgrunewald** [collective/collective.ckeditor#40]
Hello,

I'm trying to buildout the latest dev-version (4.3.0b3) of collective.ckeditor. It seems, that this process fails, see here:

> We have a develop egg: collective.ckeditor 4.3.0b3.dev0
> We have the distribution that satisfies 'plone.recipe.zope2instance==4.2.15'.
> Getting required 'ZODB3==3.10.5'
> We have the distribution that satisfies 'ZODB3==3.10.5'.
> Getting required 'Zope2==2.13.22'
> We have the distribution that satisfies 'Zope2==2.13.22'.
> Getting required 'zc.recipe.egg==1.3.2'
> We have the distribution that satisfies 'zc.recipe.egg==1.3.2'.
> Getting required 'mailinglogger==3.7.0'
> We have the distribution that satisfies 'mailinglogger==3.7.0'.
> Getting required 'setuptools==0.6c11'
> We have the distribution that satisfies 'setuptools==0.6c11'.
> Getting required 'zc.buildout==1.7.1'
> We have the distribution that satisfies 'zc.buildout==1.7.1'.
> Getting required 'demjson'
>   required by collective.ckeditor 4.3.0b3.dev0.
> We have the best distribution that satisfies 'demjson'.
> Picked: demjson = 2.2.2
> Getting required 'plone.app.uuid==1.1'
> We have the distribution that satisfies 'plone.app.uuid==1.1'.
> Getting required 'collective.plonefinder'
>   required by collective.ckeditor 4.3.0b3.dev0.
> We have a develop egg: collective.plonefinder 1.0.8.dev0
> Getting required 'collective.quickupload'
>   required by collective.plonefinder 1.0.8.dev0.
>   required by collective.ckeditor 4.3.0b3.dev0.
> We have a develop egg: collective.quickupload 1.6.7.dev0
> Getting required 'zope.i18nmessageid==3.5.3'
> We have the distribution that satisfies 'zope.i18nmessageid==3.5.3'.
> The constraint, 1.2.0, is not consistent with the requirement, 'six>=1.4'.
> While:
>   Installing instance.
> Error: Bad constraint 1.2.0 six>=1.4
> *************** PICKED VERSIONS ****************
> [versions]
> bpython = .0.14
> ipython = 3.0.0-rc1
> mccabe = 0.3
> plone.recipe.codeanalysis = 1.1.1
> plone.recipe.command = 1.1
> pyflakes = 0.8.1
> 
> #Required by:
> #collective.ckeditor 4.3.0b3.dev0
> demjson = 2.2.2
> 
> #Required by:
> #plone.recipe.codeanalysis 1.1.1
> flake8 = 2.3.0
> 
> *************** /PICKED VERSIONS ***************

I'm not sure, if collective.quickupload is responsible for this issue. My first thought was to pin it to the latest stable version, but in the [versions] section it's said, that no pin should be made. Do you have any ideas?

regards, Paul

**Comment by vincentfretin** [comment]
Simply use latest version of six.
In your versions.cfg, add 
six = 1.9.0
