### ISSUE TITLE
Release 4.3.1 seems broken?

### ISSUE THREAD

**Issue by gbastien** [collective/collective.ckeditor#47]
Hi @gotcha 

hi tried to move to version 4.3.1 but if fails when starting complaining about "ckeditor/browser/ckeditor does not exist", it seems that relevant files where not copied before release?

Could you please check and tells me if it works for you?

Thank you!

Gauthier

**Comment by ebrehault** [comment]
I have the same problem.
That's because the `browser/ckeditor` is missing in the released egg (I guess @gotcha just forgot to run `copy_ckeditor_code` before releasing).
The easiest workaround is to checkout the 4.3.1 got tag, install `copy_ckeditor_code` with buildout and run it.

**Comment by gbastien** [comment]
Hi @ebrehault,

indeed, but we need a new release because last available is broken and it is the one used by newcomers...

Happy New Year ;-)

Gauthier

**Comment by ebrehault** [comment]
@gbastien, apparently you are one of the owners of the Pypi egg, so you can push a new release (something like 4.3.1.1 I guess).

Happy new year too :)

Eric

**Comment by gbastien** [comment]
@ebrehault, you are also now :-p

Gauthier

**Comment by ebrehault** [comment]
oh cool :)
well let me update the egg then

**Comment by ebrehault** [comment]
ok done :)
https://pypi.python.org/pypi/collective.ckeditor/4.3.1.1

**Comment by gbastien** [comment]
Great!

**Comment by gbastien** [comment]
@ebrehault it seems like this new release is broken again?  Did you try it?

Maybe you need to add and commit new ckeditor folder before releasing?

Gauthier

**Comment by ebrehault** [comment]
That's strange.
Because if I generate the egg manually:
```
python setup.py bdist_egg
```
I got the right content.
But with zest releaser, the folder is missing.

I am wondering if zest releaser does consider the `.gitignore` file when generating the egg...

**Comment by ebrehault** [comment]
I have published the egg manually:
```
python setup.py sdist upload
```
I will ask @mauritsvanrees if he has an idea about this strange behavior.

**Comment by gotcha** [comment]
We all (ME INCLUDED) forgot to use `bin/fullrelease` provided in the buildout, as documented in the README.

https://pypi.python.org/pypi/collective.ckeditor/4.3.1.2#how-to-release

**Comment by gbastien** [comment]
@ebrehault thank you, works now.

Gauthier

**Comment by ebrehault** [comment]
@gotcha oh ok, well I just made a simple `bin/release`, so that's why. Thank you!

**Comment by gotcha** [comment]
@ebrehault If you did `bin/release`, the entrypoint should have been called.
I have a global `release/fullrelease` and I am pretty sure I forgot to use the local one.
Are you sure you used the local `bin/release` ?

**Comment by mauritsvanrees** [comment]
Background in case someone wonders why an entry point is needed: in the release phase, zest.releaser creates a clean clone of the repo in a temporary directory and checks out the tag. So any files that are not in version control but are created in some other way, are not in this temporary directory.

- Advantage: you have a clean checkout and do not include unwanted files, for example a copy of a python file where you did an experiment, or a file `secret_notes_for_taking_over_the_world.txt`, which are not in version control.
- Downside: to include any non version controlled files, you need to do something extra. `zest.pocompile` does this for `.mo` files.

Apparently this is needed for collective.ckeditor too, using this entry point: https://github.com/collective/collective.ckeditor/blob/4.3.1.1/src/collective/ckeditor/utils/base2zope.py#L219

Looks like both `bin/fullrelease` and `bin/release` should do the trick.
