### ISSUE TITLE
Is there any reason for loading js for anonymous users ?

### ISSUE THREAD

**Issue by bsuttor** [collective/collective.ckeditor#50]
I see in jsregistry (https://github.com/collective/collective.ckeditor/blob/master/src/collective/ckeditor/profiles/default/jsregistry.xml) than js is loaded for anonymous.
But I thing anonymous users never use ckeditor. 
So I was wondering why authenticated="True" parameters is not set ?

**Comment by gotcha** [comment]
I think you are right this could be changed to `authenticated="True"` 

If someone needs sthing else, it is easy to override anyway.

If you plan to do a release, read the README first where I tried to explain how to do it.
