### ISSUE TITLE
ajaxsave not enabled for some users non "Manager"

### ISSUE THREAD

**Issue by gbastien** [collective/collective.ckeditor#57]
Hi @gotcha 

what is the purpose of https://github.com/collective/collective.ckeditor/blame/master/src/collective/ckeditor/browser/ckeditorview.py#L559 ?  For the DX implementation, in comparison with https://github.com/collective/collective.ckeditor/blame/master/src/collective/ckeditor/browser/ckeditorview.py#L632 for the AT comparison.

I suppose this tries to detect if the cke-save view is available for the current user, but using restrictedTraverse is very restrictive and for example, if in the path, you have a folder that you can not traverse, then ajax_save is disabled.

I wonder, why are we doing this check?  Would unrestrictedTraverse solve your usecase?

Thank you,

Gauthier

**Comment by gbastien** [comment]
Hi @gotcha 
See https://github.com/collective/collective.ckeditor/blame/master/src/collective/ckeditor/browser/ckeditorview.py#L613
Thank you

**Comment by gotcha** [comment]
See 7d024687959bd021647773277afc57404f84e9eb

Released in https://pypi.org/project/collective.ckeditor/4.11.0a2/
