### ISSUE TITLE
Implement a way to define Disallowed content rules

### ISSUE THREAD

**Issue by gbastien** [collective/collective.ckeditor#58]
Hi @gotcha 

since CKeditor 4.4, it is possible to define Disallowed content rules in addition to Allowed content rules.

This makes it easy to disallow some tags or attributes.

https://ckeditor.com/docs/ckeditor4/latest/guide/dev_disallowed_content.html

Gauthier

**Comment by gbastien** [comment]
Hi @gotcha 

I see https://github.com/collective/collective.ckeditor/pull/36 that is addressing the same issue as this one...

Would you have time to work on this soon?

Thank you,

Gauthier

**Comment by gotcha** [comment]
@gbastien Can you check if #60 works for you ?

**Comment by gbastien** [comment]
Hi @gotcha 

did not catch your answer, we are going to test this!

Thank you,

Gauthier

**Comment by duchenean** [comment]
Done and released
