### ISSUE TITLE
No warning when leaving after edits without saving

### ISSUE THREAD

**Issue by ThibautBorn** [collective/collective.ckeditor#88]
If a user makes changes in Plone on an object TTW (e.g. change the description) and leaves the edit page without saving, a pop-up warning will warn the user that there changes will be lost. (for example when clicking the folder_contents in the toolbar)

If the changes are only done in ckeditor, this popup doesn't appear and the changes of the user are thrown away quietly.

**Comment by gotcha** [comment]
Should be fixed in https://pypi.org/project/collective.ckeditor/5.0.0b2/
